esphome:
  name: esphome-huawei-lte
  platform: ESP8266
  board: nodemcuv2
#  libraries: 
#  -  ${common.lib_deps}
#  - SPI 
#  - ESP8266WiFi                           
#  - ESP8266HTTPClient

http_request:
  verify_ssl: false
web_server:
  port:
external_components:
- source:
      type: local
      path: custom_components/huawei_lte
wifi:
  ssid: "your_ssid"
  password: "your_password"

huawei_lte:
    host: "http://192.168.8.1"
    username: "admin"
    password: "admin"
    id: huaweilte
sensor:
  - platform: huawei_lte
    huawei_lte_id: huaweilte
    name: "Device Information"
    type: DEVICE_INFORMATION

