esphome:
  name: esphome-huawei-lte
esp32:
  board: esp32dev
logger:
captive_portal:
web_server:
  port: 80
external_components:
  - source:
      type: local
      path: components
    components: all
wifi:
  ssid: !secret wifi
  password: !secret wifi_password

huawei_lte:
  id: huaweilte
  host: "http://192.168.8.1"
  username: "admin"
  password: "admin"
sensor:
  - platform: huawei_lte
    huawei_lte_id: huaweilte
    name: Device Information
    type: DEVICE_INFORMATION
  - platform: huawei_lte
    huawei_lte_id: huaweilte
    name: Data uploaded in current month
    type: MONITORING_MONTH
    subtype: DATA_UP



