esphome:
  name: esphome-huawei-lte
  platform: ESP8266
  board: nodemcuv2

http_request:
  verify_ssl: false
web_server:
  port: 80

external_components:
- source:
      type: local
      path: components/huawei_lte
wifi:
  ssid: "your_ssid"
  password: "your_password"
ota:
  platform: esphome


