esphome:
  name: esphome-huawei-lte

esp32:
  board: esp32dev

web_server:
  port: 80

external_components:

- source: github://Fabian-Schmidt/esphome-victron_ble

wifi:
  ssid: "your_ssid"
  password: "your_password"
#huawei_lte:
#  id: huaweilte
#  host: "http://192.168.8.1"
#  username: "admin"
#  password: "admin"
